### ISSUE TITLE
/vendor/bundle 配下をgitignoreする

### ISSUE THREAD

**Issue by ms2sato** [koizumi1227/make_blog_in_rails#1]
ignoreしないと不要な外部gemのファイルが大量にアップされてしまいます。
これをやるには二段階です。

- `git rm` を調べて（必ず調べること）、bundleのファイルは消さずにgitの管理から外す。
- `.gitignore` を調べて、今後gitに追加されていなくても無視されるようにする。

**Comment by koizumi1227** [comment]
> git rm を調べて（必ず調べること）、bundleのファイルは消さずにgitの管理から外す。

git rm --cached /vendor  でローカルファイルを残したままgit上の管理から外れます。

> .gitignore を調べて、今後gitに追加されていなくても無視されるようにする。

.gitignore へ /vendor/bundle を追記しました。

**Comment by ms2sato** [comment]
@koizumi1227 　https://github.com/koizumi1227/make_blog_in_rails/tree/master/vendor/bundle/ruby/2.5.0

このあたりの、 `vendor/bundle`配下の内容がgitに乗らなくなる想定です。今はまだ残っていそうですが、うまく対応できそうかな？見て見てください。

**Comment by koizumi1227** [comment]
@ms2sato 
勘違いしていました。git上のファイルも残したままかと思っていました。
```
git rm -r /vendor 
```
からpushし、git上のファイルも消しました！
一つ気になるのですが、今回はvendorファイルをアップし、またそれを消したことで履歴が大量に残ってしまいました。履歴を消す方法もあるそうですが、そこはチームによる判断を待ったほうがいいのでしょうか？

**Comment by ms2sato** [comment]
@koizumi1227 

> 履歴を消す方法もあるそうですが

今回のようなケースの場合には、特に気にせず放置してしまうことが多いです。あえてGitHub上から消しにゆくのは例えばセキュリティ的に問題がある場合（例えばAWSを扱っている時にキー情報をpushしたりすると、privateならまだマシですがpublicの場合にはおおごとです。要注意です）とかですね。

今回はgemの中身とかなので今は気にせずいきましょう！

**Comment by ms2sato** [comment]
@koizumi1227 ちなみにvendorディレクトリは置いておくことが多いですが、特に動かすのに支障なければこのままで大丈夫です〜。

**Comment by ms2sato** [comment]
Issue自体はこなしたのでclose。
