### ISSUE TITLE
enum を利用して、 Post に状態を作る

### ISSUE THREAD

**Issue by ms2sato** [koizumi1227/make_blog_in_rails#12]
- enum という機能があるので調べましょう（参考にしたWEBページをこのスレッドにリンクで貼ってください。どんなことができるかも一緒に文章でください）。
- Postにstatus というカラムを追加します。
  - integer
  - default: 0
- Postにenumでstatusとして以下を実装します。カッコ内は対応する数値
  - `draft`(0):  下書き
  - `published`(1) :  通常状態
  - `archived`(-1) : 一覧に表示されなくなる（アーカイブ）

結果として例えば下記のようにできるようになるはずです。　`bin/rails c` などを使って確かめましょう。

```
post = Post.last # 最後の一件を取ってきたけど、newしても良いし、findでID指定してもいい
post.published! # この瞬間にpostのstatusは1でupdateされる
```

**Comment by koizumi1227** [comment]
https://www.sejuku.net/blog/26369
カラムの値をenumによって割り当てた文字列で変更が可能になります。
例えば、都道府県のような数があるものをカラム値にすると0〜46となり、
enumを使うことで 0:hokkaido , 1:aomori , 2:akita などデータベースへ保存する際の値を文字列として割り当て、この文字列をプログラム上で使うことが可能になります。
enumを使わなければプログラム上ではその数値を使わなければならず、どの都道府県がどの値なのかを把握しないとならない。これにより値の勘違いによる設定ミスが起きたりする。
それに加え、可読性が上がります。

伊藤さんのyoutube付きの作成方法も
https://qiita.com/jnchito/items/c7e93c7a1fc7fc34a177

**Comment by ms2sato** [comment]
@koizumi1227 基本の理解はあっていますね！Railsで提供されているenumは単なる数字と名前の組み合わせよりも色々なことができるようになっています。

特に下記のようにモデルにメソッドが作成されることのメリットが大きいです。この手のものはenumを使わないと大抵手で一個ずつ書くことになるんですね。

```rb
article.status # => draft
article.draft? # => true
article.published? # => false

article.published! # statusをpublishedに変更
```

下記の記事から引用しました。最初のリンクでも同じようなこと書いてありましたね。
https://qiita.com/shizuma/items/d133b18f8093df1e9b70
