### ISSUE TITLE
一覧で表示するものを 公開済み だけに絞りましょう

### ISSUE THREAD

**Issue by ms2sato** [koizumi1227/make_blog_in_rails#14]
https://github.com/koizumi1227/make_blog_in_rails/issues/12
が終わったらやりましょう。

enumの機能を使えば簡単に情報の絞り込みができるはずです。公開済みのPostだけが一覧に出るようにしてください。

**Comment by koizumi1227** [comment]
#13 
よりも先にやらせてください！
