### ISSUE TITLE
ハッシュの書き方をなるべく新しい形で書く

### ISSUE THREAD

**Issue by ms2sato** [koizumi1227/make_blog_in_rails#2]
```
validates :title,  :presence => true
```

これは `:presence => true` の部分をもっと簡潔に書けます。調べて対応しましょう。

**Comment by koizumi1227** [comment]
presence: true
へ変更しました。

**Comment by ms2sato** [comment]
@koizumi1227 方向性大丈夫です！下記もチェックして対応してくださーい。
今後基本的には新しい書き方で行ってくださいね！

https://github.com/koizumi1227/make_blog_in_rails/commit/2109fcde9e0589d3be261e2772e657a83851a7d6#r27551722

**Comment by ms2sato** [comment]
大丈夫そうなのでclose
