### ISSUE TITLE
ログインユーザーの投稿管理を別のコントローラーにする

### ISSUE THREAD

**Issue by ms2sato** [koizumi1227/make_blog_in_rails#25]
※本当はもう少し別の形も使うのですが、今は簡易的に進めます。

`ManagePostsController` というコントローラを作ります。このコントローラーはユーザーのPost編集や投稿ポスト一覧などのログイン後ユーザーのできる操作を司るコントローラーです。

今、 `PostsController` はコントローラ内でログインしているかをチェックしながらこれを行なっていると思いますが、こちらのコントローラを導入して、うまく分解してください（今の状態はそのまま開発を続けるとどんどん扱いづらくなります）。

一旦丸投げ的に渡してみるので考えてみてくださいね。もしもやるべきことがよくわからない場合には質問ください。

**Comment by koizumi1227** [comment]
とりあえずやってみます。
