### ISSUE TITLE
PullRequestを送る準備

### ISSUE THREAD

**Issue by ms2sato** [koizumi1227/make_blog_in_rails#3]
PullRequestというとても便利な機能がGitHubにはあります。これを目指して下記のようなことを勉強して欲しいです。

- gitのブランチの作成する方法
- ローカルで作成したブランチをGitHubへ送る方法
- PullRequestを作成する

簡単にテスト用のブランチをこのリポジトリで作って試して大丈夫です。

**Comment by koizumi1227** [comment]
```
git checkout -b test-user
```
ブランチを作成しそのままtest-userへbranch へ切り替えしました。
```
git push origin test-user 
```
testfileをあらかじめ作り、commitをしておいたのでそれをpushしました。（pushしたファイルをpullreqへ使うため）
その後、githubからpullreq しました！

以上で上記の３つを実験できたかと思います！
