### ISSUE TITLE
日記へcomment欄を追加

### ISSUE THREAD

**Issue by koizumi1227** [koizumi1227/make_blog_in_rails#5]
それぞれの日記へコメントができる欄を追加。
commenter　をコメントした人の名前
comment　をコメント内容
とし、commentsテーブルを作り、ログイン認証の必要なくコメントできるように。
ただし、削除するにはログインが必要。

**Comment by ms2sato** [comment]
お、削除だけログイン必要とは変わった仕様。興味深いです。
