### ISSUE TITLE
記事へ画像アップロードを追加する

### ISSUE THREAD

**Issue by koizumi1227** [koizumi1227/make_blog_in_rails#7]
記事へ画像を追加できるようにする。
carrier wave gemで作成します。（paperclipも気になりますが次の機会に）

記事一覧と記事のそれぞれのページで表示させる予定です。
一覧では画像を少し縮小して表示（それぞれのページ表示での画像を基準とする）
アップロードサイズは最大５MBとする。

**Comment by ms2sato** [comment]
@koizumi1227 いいIssueですね！Carrierwaveはよく使われているので、やってみると良いですよ。
