### ISSUE TITLE
バリデーションチェックを入れて、画面でユーザに再入力が促されるようにする

### ISSUE THREAD

**Issue by ms2sato** [koizumi1227/make_blog_in_rails#8]
- 新規PostやCommentで、入力文字数が多かったり、入っていなかったりした場合にエラー表示をしたいです（例: 'xxxは必須です'
- Railsには標準的にこれのやり方が用意されているので、調べて実装してみましょう。

**Comment by koizumi1227** [comment]
@ms2sato 
画像アップが終わり次第とりかかります！
